//
// Generated by JTB 1.3.2 DIT@UoA patched
//

package syntaxtree;

/**
 * Grammar production:
 * f0 -> "join"
 * f1 -> "["
 * f2 -> Condition()
 * f3 -> "]"
 * f4 -> "("
 * f5 -> Relation()
 * f6 -> ")"
 * f7 -> "("
 * f8 -> Relation()
 * f9 -> ")"
 */
public class JoinOp implements Node {
   public NodeToken f0;
   public NodeToken f1;
   public Condition f2;
   public NodeToken f3;
   public NodeToken f4;
   public Relation f5;
   public NodeToken f6;
   public NodeToken f7;
   public Relation f8;
   public NodeToken f9;

   public JoinOp(NodeToken n0, NodeToken n1, Condition n2, NodeToken n3, NodeToken n4, Relation n5, NodeToken n6, NodeToken n7, Relation n8, NodeToken n9) {
      f0 = n0;
      f1 = n1;
      f2 = n2;
      f3 = n3;
      f4 = n4;
      f5 = n5;
      f6 = n6;
      f7 = n7;
      f8 = n8;
      f9 = n9;
   }

   public JoinOp(Condition n0, Relation n1, Relation n2) {
      f0 = new NodeToken("join");
      f1 = new NodeToken("[");
      f2 = n0;
      f3 = new NodeToken("]");
      f4 = new NodeToken("(");
      f5 = n1;
      f6 = new NodeToken(")");
      f7 = new NodeToken("(");
      f8 = n2;
      f9 = new NodeToken(")");
   }

   public void accept(visitor.Visitor v) {
      v.visit(this);
   }
   public <R,A> R accept(visitor.GJVisitor<R,A> v, A argu) {
      return v.visit(this,argu);
   }
   public <R> R accept(visitor.GJNoArguVisitor<R> v) {
      return v.visit(this);
   }
   public <A> void accept(visitor.GJVoidVisitor<A> v, A argu) {
      v.visit(this,argu);
   }
}

